### ISSUE TITLE
Renamed asyncBootsrap to bootstrap for v2 but still see warning

### ISSUE THREAD

**Issue by codeBelt** [ctrlplusb/react-async-bootstrapper#9]
Updated both my JavaScript and TypeScript example projects. Renamed asyncBootsrap to bootstrap and still get the warning:

`"react-async-bootstrapper" deprecation notice: please rename your "asyncBootsrap" methods to "bootstrap"`

[JavaScript](https://github.com/codeBelt/hapi-react-hot-loader-example/pull/35/files) Changes
[TypeScript](https://github.com/codeBelt/typescript-hapi-react-hot-loader-example/pull/19/files) Changes

**Comment by ctrlplusb** [comment]
Dropped a review on your PR 👍
